version: "3"

services:
  registry:
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/${HOST_NAME}.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/${HOST_NAME}.key"
    image: registry:latest
    ports:
      - "${HOST_IP}:5000:5000"
    restart: always
    volumes:
      - "./overlay/auth/:/auth/"
      - "./overlay/certs/:/certs/"
      - "registry:/var/lib/registry"

volumes:
  registry: