version: "3"

services:
  registry:
    domainname: "${DOMAIN_NAME}"
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/${HOST_NAME}.${DOMAIN_NAME}.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/${HOST_NAME}.${DOMAIN_NAME}.key"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    image: registry:2
    hostname: "${HOST_NAME}"
    ports:
      - "${HOST_IP}:5000:5000"
    restart: always
    volumes:
      - "auth:/auth"
      - "./overlay/certs/:/certs/"
      - "registry:/var/lib/registry"

volumes:
  auth:
  registry:
