version: "3"

services:
  registry:
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/${hostname}.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/${hostname}.key"
    image: registry:latest
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "./data/auth/:/auth/"
      - "./data/certs/:/certs/"
      - "registry:/var/lib/registry"

volumes:
  registry: